require_relative 'common'
require 'zlib'
require 'stringio'

class StringPool
  PoolItemInfo = Struct.new(:offset, :length)
  def initialize(align = 0)
    @buf = StringIO.new
    @hash = {}
    @align = align
  end
  def add(str)
    return @hash[str] if @hash.key?(str)
    offset = @buf.length
    length = str.length
    @buf.write(str)
    if @align != 0 && @buf.length % @align != 0
      @buf.write(' '*(-(@buf.length % -@align)))
    end
    info = PoolItemInfo.new(offset, length)
    @hash[str] = info
    info
  end

  def pool
    @buf.string
  end
end

def emit_type(io, pool, type)
  csname = check_csharp_keyword type.name
  io.puts "partial class #{csname}Converter"
  io.puts "{"
  io.block do
    io.puts "internal override void TdJsonWriteItems(TdJsonWriter writer, TLObject tlobj)"
    io.puts "{"
    io.block do
      str = %Q[{"@type":"#{type.realname}"]
      poolitem = pool.add(str)
      io.puts "writer.WriteSpan(StringPool.Slice(#{poolitem.offset}, #{poolitem.length})); // #{str}"
      unless type.props.empty?
        io.puts "var obj = (#{csname})tlobj;"
      end
      type.props.each do |prop|

        propname = prop.capname
        if propname == type.name
          propname = "#{propname}_"
        end
        csname = check_csharp_keyword propname
        str = %Q{,"#{prop.name}":}
        poolitem = pool.add(str)

        case 
        when prop.type == "byte[]"
          io.puts "if (obj.#{csname} != null)"
          io.puts "{"
          io.block do
            io.puts "writer.WriteSpan(StringPool.Slice(#{poolitem.offset}, #{poolitem.length})); // #{str}"
            io.puts "writer.WriteBytesValue(obj.#{csname});"
          end
          io.puts "}"
        when prop.type.is_a?(String) # other primitive type
          io.puts "writer.WriteSpan(StringPool.Slice(#{poolitem.offset}, #{poolitem.length})); // #{str}"
          io.puts "writer.WriteValue(obj.#{csname});"
        when prop.type == TDLibTLTypeInfo::Int64
          io.puts "writer.WriteSpan(StringPool.Slice(#{poolitem.offset}, #{poolitem.length})); // #{str}"
          io.puts "writer.WriteInt64String(obj.#{csname});"
        when prop.type == TDLibTLTypeInfo::Vector[TDLibTLTypeInfo::Int64]
          io.puts "if (obj.#{csname} != null)"
          io.puts "{"
          io.block do
            io.puts "writer.WriteSpan(StringPool.Slice(#{poolitem.offset}, #{poolitem.length})); // #{str}"
            io.puts "writer.WriteInt64Array(obj.#{csname});"
          end
          io.puts "}"
        when prop.type.is_a?(Class) && prop.type <= TDLibTLTypeInfo::Vector
          io.puts "if (obj.#{csname} != null)"
          io.puts "{"
          io.block do
            io.puts "writer.WriteSpan(StringPool.Slice(#{poolitem.offset}, #{poolitem.length})); // #{str}"
            io.puts "writer.WriteArray(obj.#{csname});"
          end
          io.puts "}"
        else
          io.puts "if (obj.#{csname} != null)"
          io.puts "{"
          io.block do
            io.puts "writer.WriteSpan(StringPool.Slice(#{poolitem.offset}, #{poolitem.length})); // #{str}"
            io.puts "writer.WriteValue(obj.#{csname});"
          end
          io.puts "}"
        end
      end
      # io.puts "TdJsonWriteExtra(writer, ref tlobj);"
      # io.puts "writer.WriteEndObject();"

    end
    io.puts "}"
  end
  io.puts "}"
  io.puts ""
end

def emit(codeout, pooloutfile)
  io = IndentedOutput.new(codeout)
  io.puts "// generated by codegen/genwriter.rb"
  io.puts "using System;"
  io.puts "using TDLib.Api;"
  io.puts ""
  io.puts "namespace TDLib.JsonClient"
  io.puts "{"
  io.push

  pool = StringPool.new(8)


  extraitem = pool.add(%Q{,"@extra":})
  io.puts "partial class TdJsonWriter"
  io.puts "{"
  io.block do
    io.puts "private const int _extrapos = #{extraitem.offset};"
    io.puts "private const int _extralen = #{extraitem.length};"
  end
  io.puts "}"

  TDLibTLTypeInfo::Types.each_value do |type|
    emit_type(io, pool, type)
  end

  TDLibTLTypeInfo::Functions.each_value do |type|
    emit_type(io, pool, type)
  end

  crc = Zlib::crc32(pool.pool)

  io.puts "partial class StringPool"
  io.puts "{"
  io.block do
    io.puts "private const uint _poolcrc = #{'0x%08Xu' % crc};"
  end
  io.puts "}"
  io.puts ""

  io.pop
  io.puts "}"

  IO.binwrite(pooloutfile, pool.pool)
end

TDLibTLTypeInfo.load ARGV[0]
emit File.open(ARGV[1], 'wb'), ARGV[2]
